name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run ESLint
      uses: hallee/eslint-action@1.0.1
    - name: Run pylint
      uses: cclauss/GitHub-Action-for-pylint@0.0.1
